version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
      - OAUTH_AUTHORITY=$OAUTH_AUTHORITY
      - OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET
      - OAUTH_REDIRECT_URI=$OAUTH_REDIRECT_URI
      - PORT=$PORT
      - ELASTIC_NODE=$ELASTIC_NODE
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
